ProjeVek.WebUI.Site/Models/CategoryViewModel.cs
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace ProjeVek.WebUI.Site.Models
{
    public class CategoryViewModel
    {
        public CategoryViewModel()
        {
            Category = new Model.Category();
            Contents = new List<Model.Content>();
        }

        public Model.Category Category { get; set; }
        public List<Model.Content> Contents { get; set; }

        public int CurrentPage { get; set; }
        public int TotalData { get; set; }
        public double TotalPage { get; set; }

    }
}

ProjeVek.WebUI.Site/Controllers/CategoryController.cs
using Microsoft.AspNetCore.Mvc;
using ProjeVek.Data;
using ProjeVek.WebUI.Site.Models;
using System;
using System.Linq;

namespace ProjeVek.WebUI.Site.Controllers
{
    public class CategoryController : Controller
    {
        CategoryData _categoryData;
        ContentData _contentData;
        ContentCategoryData _contentCategoryData;

        public CategoryController(CategoryData _categoryData, ContentData _contentData, ContentCategoryData _contentCategoryData)
        {
            this._categoryData = _categoryData;
            this._contentData = _contentData;
            this._contentCategoryData = _contentCategoryData;
        }

        public IActionResult Index(string slug, int page = 1)
        {
            var category = _categoryData.GetBy(x => x.Slug == slug && x.IsActive && !x.IsDeleted).FirstOrDefault();
            if (category == null)
                return RedirectToAction("Index", "Home", new { q = "kategori-bulunamadi" });

            var category_content_ids = _contentCategoryData.GetByPage(x => x.CategoryId == category.Id, page, 10)
                .Select(x => x.ContentId).ToList();
            var total_data = _contentCategoryData.GetCount(x => x.CategoryId == category.Id);
            double c = double.Parse(total_data.ToString()) / 10;
            c = Math.Ceiling(c);

            var contents = _contentData.GetContentsByIds(category_content_ids, 10);

            var model = new CategoryViewModel()
            {
                Category = category,
                Contents = contents,
                CurrentPage = page,
                TotalData = total_data,
                TotalPage = c,
            };

            return View(model);
        }
    }
}

ProjeVek.WebUI.Site/Controllers/ContentController.cs
using Microsoft.AspNetCore.Mvc;
using ProjeVek.Data;
using System.Collections.Generic;
using System;
using System.Linq;
using ProjeVek.WebUI.Site.Models;

namespace ProjeVek.WebUI.Site.Controllers
{
    public class ContentController : Controller
    {
        ContentData _contentData;
        ContentCategoryData _contentCategoryData;

        public ContentController(ContentData _contentData, ContentCategoryData _contentCategoryData)
        {
            this._contentData = _contentData;
            this._contentCategoryData = _contentCategoryData;
        }

        public IActionResult Index(string slug)
        {
            var content = _contentData.GetContentBySlug(slug);
            if (content == null)
                return RedirectToAction("Index", "Home", new { q = "makale-bulunamadi" });

            var category = _contentCategoryData.GetBy(x => x.ContentId == content.Id).FirstOrDefault();
            var relateds = new List<Model.Content>();

            if (category != null)
            {
                var category_content_ids = _contentCategoryData.GetBy(x => x.CategoryId == category.Id)
                .Take(6).Select(x => x.ContentId).ToList();

                relateds = _contentData.GetContentsByIds(category_content_ids, 6);
            }
            else
            {
                var dtNow = DateTime.Now;
                relateds = _contentData.GetBy(x => x.IsActive && !x.IsDeleted && x.PublishDate <= dtNow);
            }

            var model = new ContentViewModel()
            {
                Content = content,
                Relateds = relateds,
            };

            return View(model);
        }
    }
}

ProjeVek.WebUI.Site/Views/Category/Index.cshtml
@model CategoryViewModel
@{
    ViewBag.Title = "Kategori";
}

<div class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
            <div class="col-md-8 animate-box" data-animate-effect="fadeInLeft">
                <div>
                    <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">@Model.Category.Name</div>
                </div>

                @foreach (var item in Model.Contents)
                {
                    <div class="row pb-4">
                        <div class="col-md-5">
                            <div class="fh5co_hover_news_img">
                                <div class="fh5co_news_img">
                                    @if (item.Media != null)
                                    {
                                        <img src="@item.Media.MediaUrl" alt="" />
                                    }
                                    else
                                    {
                                        <img src="images/nathan-mcbride-229637.jpg" alt="" />
                                    }
                                </div>
                                <div></div>
                            </div>
                        </div>
                        <div class="col-md-7 animate-box">
                            <a href="@Url.Action("Index","Content", new { slug = item.Slug })" class="fh5co_magna py-2">
                                @item.Title
                            </a> <a href="@Url.Action("Index","Content", new { slug = item.Slug })" class="fh5co_mini_time py-3">
                                @if (item.Author != null)
                                {
                                    @item.Author.Fullname <span>-</span>
                                }
                                @item.PublishDate.ToString("dd MMMM yyyy")
                            </a>
                            <div class="fh5co_consectetur">
                                @item.MetaDescription
                            </div>
                        </div>
                    </div>
                }
            </div>
            @await Html.PartialAsync("_SideBar")
        </div>

        @if (Model.TotalPage > 1)
        {
            <div class="row mx-0">
                <div class="col-12 text-center pb-4 pt-4">

                    @if (Model.CurrentPage == 1)
                    {
                        var next = Model.CurrentPage + 1;
                        <a href="#" class="btn_pagging">@Model.CurrentPage</a>
                        <a href="@Url.Action("Index","Category", new { page = next, slug = Model.Category.Slug })" class="btn_mange_pagging">İleri <i class="fa fa-long-arrow-right"></i></a>
                    }
                    else
                    {
                        if (Model.TotalPage > Model.CurrentPage)
                        {
                            var next = Model.CurrentPage + 1;
                            var prev = Model.CurrentPage - 1;

                            <a href="@Url.Action("Index","Category", new { page = prev, slug = Model.Category.Slug })" class="btn_mange_pagging"><i class="fa fa-long-arrow-left"></i> Geri</a>
                            <a href="#" class="btn_pagging">@Model.CurrentPage</a>
                            <a href="@Url.Action("Index","Category", new { page = next, slug = Model.Category.Slug })" class="btn_mange_pagging">İleri <i class="fa fa-long-arrow-right"></i></a>
                        }
                        else
                        {
                            var prev = Model.CurrentPage - 1;

                            <a href="@Url.Action("Index","Category", new { page = prev, slug = Model.Category.Slug })" class="btn_mange_pagging"><i class="fa fa-long-arrow-left"></i> Geri</a>
                            <a href="#" class="btn_pagging">@Model.CurrentPage</a>
                        }
                    }
                </div>
            </div>
        }
    </div>
</div>